name: Build ImmortalWrt Firmware

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install build-essential clang flex bison g++ gawk \
        gcc-multilib g++-multilib gettext git libncurses5-dev \
        libssl-dev python3-distutils rsync unzip zlib1g-dev file wget

    - name: Update feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Generate config
      run: |
        echo "CONFIG_TARGET_mediatek=y" > .config
        echo "CONFIG_TARGET_mediatek_filogic=y" >> .config
        echo "CONFIG_TARGET_mediatek_filogic_DEVICE_cudy_tr3000-v1=y" >> .config
        make defconfig

    - name: Build firmware
      run: |
        make -j$(nproc) || make -j1 V=s

    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: immortalwrt-cudy-tr3000-v1
        path: bin/targets/mediatek/filogic/*.bin
