name: Build ImmortalWrt Firmware

on:
  # 仅在手动触发时编译
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex bison g++ gawk \
              gcc-multilib g++-multilib gettext git libncurses5-dev \
              libssl-dev python3-distutils rsync unzip zlib1g-dev file wget

      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Generate config
        run: |
          # 指定 MTK 平台 + Filogic 子平台 + Cudy TR3000
          echo "CONFIG_TARGET_mediatek=y" > .config
          echo "CONFIG_TARGET_mediatek_filogic=y" >> .config
          echo "CONFIG_TARGET_mediatek_filogic_DEVICE_cudy_tr3000-v1=y" >> .config

          # 设置 rootfs 大小为 112MB
          # 若不需要 112MB，可去掉或者改成其它值
          echo "CONFIG_TARGET_ROOTFS_PARTSIZE=112" >> .config

          # 根据当前源码默认配置展开
          make defconfig

      - name: Build firmware
        run: |
          # 多线程编译，失败则单线程输出详细日志
          make -j"$(nproc)" || make -j1 V=s

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          # 生成的固件名称自定义
          name: immortalwrt-cudy-tr3000-v1
          # 指定固件输出路径，视源码情况修改
          path: bin/targets/mediatek/filogic/*.bin
